const orders = [
  {
    id: 1,
    orderNo: 2,
    order_date_time: "02/04/2024 10:20 AM",
    delivery_assigned: 2,
    isDeliveryDelayed: false,
    orderStatus: 2,
    status: {
      id: 2,
      name: "Delivered",
    },
    assignedUser: {
      id: 2,
      name: "Steve",
      createdAt: "01/01/2024",
    },
    address: {
      lat: 25.22,
      lng: 740.01,
      city: "Chennai",
      state: "Tamilnadu",
      street: "5th Street",
      area: "Navalur",
      landMark: "Main Road",
      pinCode: 600097,
    },
  },
  {
    id: 2,
    orderNo: 3,
    order_date_time: "02/04/2024 10:40 AM",
    delivery_assigned: 2,
    isDeliveryDelayed: true,
    orderStatus: 1,
    status: {
      id: 1,
      name: "Cutting",
    },
    assignedUser: {
      id: 1,
      name: "Cham",
      createdAt: "03/01/2024",
    },
    address: {
      lat: 20.22,
      lng: 140.01,
      city: "Chennai",
      state: "Tamilnadu",
      street: "5th Street",
      area: "Navalur",
      landMark: "Main Road",
      pinCode: 600097,
    },
  },
  {
    id: 3,
    orderNo: 4,
    order_date_time: "02/04/2024 11:20 AM",
    delivery_assigned: 2,
    isDeliveryDelayed: false,
    orderStatus: 2,
    status: {
      id: 2,
      name: "Delivered",
    },
    assignedUser: {
      id: 2,
      name: "Steve",
      createdAt: "01/01/2024",
    },
    address: {
      lat: 20.22,
      lng: 140.01,
      city: "Chennai",
      state: "Tamilnadu",
      street: "5th Street",
      area: "Thalambur",
      landMark: "Post Office",
      pinCode: 600097,
    },
  },
  {
    id: 4,
    orderNo: 5,
    order_date_time: "02/04/2024 11:20 AM",
    delivery_assigned: 1,
    isDeliveryDelayed: false,
    orderStatus: 1,
    status: {
      id: 1,
      name: "Delivered",
    },
    assignedUser: {
      id: 1,
      name: "Steve",
      createdAt: "01/01/2024",
    },
    address: {
      lat: 10.22,
      lng: 210.101,
      city: "Chennai",
      state: "Tamilnadu",
      street: "2th Street",
      area: "Thalambur",
      landMark: "Post Office",
      pinCode: 600097,
    },
  },
];

const orderDetail = {
  orderNo: 5,
  order_date_time: "02/04/2024 11:20 AM",
  delivery_assigned: 1,
  isDeliveryDelayed: true,
  orderStatus: 1,
  orderedProducts: {
    orderedProductId: 22,
    products: [
      {
        id: 1,
        name: "Chicken",
        quantity: "500 g",
        category: {
          id: 1,
          name: "Meat",
        },
      },
      {
        id: 2,
        name: "Mutton",
        quantity: "1 kg",
        category: {
          id: 1,
          name: "Meat",
        },
      },
      {
        id: 3,
        name: "Prawn",
        quantity: "240 g",
        category: {
          id: 1,
          name: "Meat",
        },
      },
    ],
  },
  status: {
    id: 1,
    name: "Cleaning",
  },
  assignedUser: {
    id: 1,
    name: "Steve",
    createdAt: "01/01/2024",
    adharNo: 3023323232343,
    licence: "TN9393943434",
    status: "Active",
    address: {
      lat: 104.22,
      lng: 210.101,
      street: "1th Street",
      area: "Thalambur",
      city: "Chennai",
      state: "Tamilnadu",
      landMark: "Bus Stop",
      pinCode: 600097,
    },
  },
  address: {
    lat: 10.22,
    lng: 210.101,
    street: "2th Street",
    area: "Thalambur",
    city: "Chennai",
    state: "Tamilnadu",
    landMark: "Post Office",
    pinCode: 600097,
  },
};

export { orders, orderDetail };
